routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('site');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArticleController');
    Route::resource('usuarios', 'UserController');
    Route::resource('autores', 'AuthorController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Article extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $fillable = ['id','title', 'content', 'description','date'];

    /**
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    /**
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public static function getAllArticles($paginate)
    {
        return DB::table('articles')
                ->join('users', 'users.id', '=', 'articles.user_id')
                ->select(
                    'articles.id',
                    'articles.title',
                    'articles.description',
                    'users.name',
                    'articles.date')
                ->whereNull('deleted_at')
                ->paginate($paginate);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Article;
use Validator;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('dashboard')],
            ['title' => 'Lista de Artigos', 'url' => ''],
        ]);

        // $articles = Article::select('id', 'title', 'description','user_id', 'date')->paginate(2);

        $articles = Article::getAllArticles(5);

        return view('admin.article.index', compact('breadcrumbs', 'articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Var_dump
        // dd($request->all());

        $data = $request->all();

        $validator = Validator::make($data, [
            'title' => 'required|unique:articles|max:255',
            'description'  => 'required',
            'date' => 'required'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }


        Article::create($data);

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Article::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'title' => 'required|max:255',
            'description'  => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }


        Article::find($id)->update($data);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/article/index.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Artigos" bg="info">

            <!-- alerta se ocorrer algum erro -->
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <alert message="{{$val}}"></alert>
                @endforeach
            @endif

            <table-list
                    v-bind:titles="['#', 'Título', 'Descrição', 'Autor', 'Data']"
                    v-bind:items="{{ json_encode($articles) }}"
                    create="#new"
                    details="{{ route('artigos.index') }}"
                    edit="{{ route('artigos.index') }}"
                    exclude="{{ route('artigos.index') }}"
                    token="{{ csrf_token() }}" orderby="desc" ordercol="0" modal="true"
            ></table-list>
        </panel>
        <div class="float-right my-2">
            <!-- Método que monta a paginação -->
            {{ $articles->links() }}
        </div>
    </page>
    <!-- Criação -->
    <modal-body name="createModal" size="md" title="Adicionar Artigo">
        <form-head id="createArticle" css="" action="{{ route('artigos.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
            <div class="form-group">
                <label class="sr-only" for="title"> Título </label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Título" value="{{ old('title') }}"/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="description"> Description </label>
                <input type="text" class="form-control" id="description" name="description" placeholder="Descrição" value="{{ old('description') }}"/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="date"> Data </label>
                <input type="datetime-local" class="form-control" id="date" name="date" value="{{ old('date') }}"/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="contentCreate"> Conteúdo </label>
                <editor id="contentCreate" content="{{ old('content') }}"></editor>
            </div>
        </form-head>
        <span slot="buttons">
            <button form="createArticle" names="true" class="btn btn-success" value="{{ old('data') }}">Salvar</button>
        </span>
    </modal-body>
    <!-- Edição -->
    <modal-body name="editModal" size="md" title="Editar Artigo">
        <form-head id="editArticle" css="" v-bind:action="'{{ route('artigos.index') }}' + '/' + $store.state.item.id" method="put" enctype="multipart/form-data" token="{{ csrf_token() }}">
            <div class="form-group">
                <label class="sr-only" for="title"> Título </label>
                <input type="text" class="form-control" id="title" name="title" v-model="$store.state.item.title" placeholder="Título" />
            </div>
            <div class="form-group">
                <label class="sr-only" for="description"> Description </label>
                <input type="text" class="form-control" id="description" v-model="$store.state.item.description" name="description" placeholder="Descrição" />
            </div>
            <div class="form-group">
                <label class="sr-only" for="date"> Data </label>
                <input type="text" class="form-control" id="date" name="date" v-model="$store.state.item.date" readonly/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="contentEdit"> Conteúdo </label>
                <editor id="contentEdit" :content="$store.state.item.content"></editor>
            </div>
        </form-head>
        <span slot="buttons">
            <button form="editArticle" class="btn btn-success">Atualizar</button>
        </span>
    </modal-body>
    <!-- Detalhes -->
    <modal-body name="detailsModal" size="md" v-bind:title="$store.state.item.title" form="detailsArticle">
        <p>@{{$store.state.item.description}}</p>
        <p>@{{$store.state.item.content}}</p>
        <p>@{{$store.state.item.date}}</p>
    </modal-body>
@endsection