routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('site');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArticleController');
    Route::resource('usuarios', 'UserController');
    Route::resource('autores', 'AuthorController');
});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <page size="10">
        <panel title="Dashboard" bg="info">
            <div class="row">
                <div class="col-md-4" >
                    <box qtd="{{ $collection['articles'] }}" title="Artigos" bg="#00c0ef" icon="fa fa-newspaper-o" url="{{route('artigos.index')}}"></box>
                </div>
                <div class="col-md-4" >
                    <box qtd="{{ $collection['users'] }}" title="Usuários" bg="#dd4b39" icon="fa fa-users" url="{{route('usuarios.index')}}"></box>
                </div>
                <div class="col-md-4" >
                    <box qtd="{{ $collection['authors'] }}" title="Autores" bg="#00a65a" icon="fa fa-user" url="{{route('autores.index')}}"></box>
                </div>
            </div>
        </panel>
    </page>
@endsection

resources/views/site.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">

        <div class="card-group">
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
            <panel-group grid="4" title="Título" resume="resume" label="Leia mais" url="#post"></panel-group>
        </div>
    </page>
@endsection