routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('site');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArticleController');
    Route::resource('usuarios', 'UserController');
    Route::resource('autores', 'AuthorController');
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Validator;
use Illuminate\Validation\Rule;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('dashboard')],
            ['title' => 'Lista de Autores', 'url' => ''],
        ]);

        $collection = User::select('id', 'name', 'email')
            ->where('author','=','1')
            ->paginate(2);

        return view('admin.author.index', compact('breadcrumbs', 'collection'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'name' => 'required|string|max:255',
            'email'  => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $data['password'] = bcrypt($data['password']);


        User::create($data);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return User::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        if(isset($data['password']) && !empty($data['password'])):
            $validator = Validator::make($data, [
                'name' => 'required|string|max:255',
                'email'  => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
                'password' => 'required|string|min:6'
            ]);
        else:
            $validator = Validator::make($data, [
                'name' => 'required|string|max:255',
                'email'  => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
            ]);
            unset($data['password']);
        endif;

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }


        User::find($id)->update($data);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/author/index.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Autores" bg="info">

            <!-- alerta se ocorrer algum erro -->
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <alert message="{{$val}}"></alert>
                @endforeach
            @endif

            <table-list
                    v-bind:titles="['#', 'Nome', 'email']"
                    v-bind:items="{{ json_encode($collection) }}"
                    create="#new"
                    details="{{ route('autores.index') }}"
                    edit="{{ route('autores.index') }}" orderby="desc" ordercol="0" modal="true"
            ></table-list>
        </panel>
        <div class="float-right my-2">
            <!-- Método que monta a paginação -->
            {{ $collection->links() }}
        </div>
    </page>
    <!-- Criação -->
    <modal-body name="createModal" size="md" title="Adicionar Autor">
        <form-head id="createForm" css="" action="{{ route('autores.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
            <div class="form-group">
                <label class="sr-only" for="name"> Nome </label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Nome" value="{{ old('name') }}"/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="email"> Email </label>
                <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{ old('email') }}"/>
            </div>
            <div class="form-group">
                <label class="sr-only" for="author"> Autor </label>
                <select class="form-control" id="author" name="author">
                    <option v-if="{{ ( old('author') && old('author') == 0 ? 'selected': '' ) }}" value="0">Não</option>
                    <option v-if="{{ ( old('author') && old('author') == 1 ? 'selected': '' ) }}" value="1">Sim</option>
                </select>
            </div>
            <div class="form-group">
                <label class="sr-only" for="password"> Senha </label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Senha" value="{{ old('password') }}"/>
            </div>
        </form-head>
        <span slot="buttons">
            <button form="createForm" class="btn btn-success" value="{{ old('data') }}">Salvar</button>
        </span>
    </modal-body>
    <!-- Edição -->
    <modal-body name="editModal" size="md" title="Editar Autor">
        <form-head id="editForm" css="" v-bind:action="'{{ route('autores.index') }}' + '/' + $store.state.item.id" method="put" enctype="multipart/form-data" token="{{ csrf_token() }}">
            <div class="form-group">
                <label class="sr-only" for="name"> Nome </label>
                <input type="text" class="form-control" id="name" name="name" v-model="$store.state.item.name" placeholder="Name" />
            </div>
            <div class="form-group">
                <label class="sr-only" for="email"> Email </label>
                <input type="email" class="form-control" id="email" v-model="$store.state.item.email" name="email" placeholder="E-mail" />
            </div>
            <div class="form-group">
                <label class="sr-only" for="author"> Autor </label>
                <select class="form-control" id="author" name="author" v-model="$store.state.item.author">
                    <option value="0">Não</option>
                    <option value="1">Sim</option>
                </select>
            </div>
            <div class="form-group">
                <label class="sr-only" for="password"> Senha </label>
                <input type="password" class="form-control" id="password" v-model="$store.state.item.password" name="password" placeholder="Senha" />
            </div>
        </form-head>
        <span slot="buttons">
            <button form="editForm" class="btn btn-success">Atualizar</button>
        </span>
    </modal-body>
    <!-- Detalhes -->
    <modal-body name="detailsModal" size="md" v-bind:title="$store.state.item.name" form="detailsForm">
        <p>@{{$store.state.item.email}}</p>
    </modal-body>
@endsection